### PR TITLE
Tutorial 15 : First principles calculation of U and J

### PR DESCRIPTION
**Pull request by Nekkrad**
A new tutorial that explains how to compute U and J from first principles using ONETEP and the minimum tracking method.

It is a first draft so I am very open to corrections and suggestions on how to improve it.

I'll tag the relevant people and attach the pdf

@JacekDziedzic
@david-oregan 
[oneteptutorials.pdf](https://github.com/user-attachments/files/16532425/oneteptutorials.pdf)

### CODE REVIEW

**Comment by JacekDziedzic** [comment]
Unsure if we are allowed to publish the OTF pseudos. Apart from that, I only have cosmetic comments. It would be good if a native speaker could polish the text a little.

s/if not refer/if not, refer/
s/choosing and empirical/choosing an empirical/
s/which allow us/which allows us/
s/and label it differently/for, and label it differently/
s/single points calculations/single-point calculations/
s/which corresponds to d-orbitals/, which corresponds to d orbitals./
s/input file the one/input file -- the one/
s/both \alpha and \alpha you need/both \alpha and \beta, you need/
s/remaining 8 file/remaining 8 files/
s/which can be found in the/, which can be found in the/ [twice]
s/note that we are/Note that we are/
s/Next we need/Next, we need/
s/the total occupancy of/The total occupancy of/
s/while local magnetic moment/while the local magnetic moment/
s/the slope we first/the slope, we first/
s/with values of beta to/with values of \beta to/
s/this is VERY/, this is VERY/
s/we would retrieve a wrong value/we would obtain a wrong value/

In the enumeration in 16.2.2 choose whether you use commas between list items and lowercase letters to begin list items, or full stops and capital letters.
In item 4, italicise U and J.
In the formulas that follow, unitalicise 'xc' and 'local'
Missing full stop after \beta at end of p.107.
The list of 7 items under the table is missing full stops.
"The default projectors are NGWFs" -- what other options are there? How do we choose them?
In item 7, at least in the PDF, the \beta did not render correctly, I see the literal text :math:`beta`.
Any reason for "0.00" and not "0.0" in the table?
Italicise U in "for the U calculation are".
Add full stop after "We now have all the data we need to compute U and J"
Add full stops after list items in "Step by step to..."

**Comment by david-oregan** [comment]
Hi Jacek

Thanks for your careful checking, much appreciated.

Hi Davide

Great job here. Just some further suggestions from me

The reason behind computing the parameters via first principles is because they directly correct the spurious self-interaction error and hence the physics of the system, while choosing and empirical 𝑈 and 𝐽 might give a better description of a specific property of the material, it does not guarantee that the self-interaction is fully corrected.
=>
The reason behind computing the parameters via first principles is because they directly correct the spurious localised self-interaction error (U) and static correlation error (J) and hence the physics of the system. While choosing and empirical 𝑈 and 𝐽 might give a better description of a specific property of the material, it does not guarantee that these errors are consistently corrected.

Remove
The basic idea is to compare the response of the system to a perturbation in the DFT and in the DFT+𝑈 frameworks.
Remove
We then iterate until self-consistency is achieved.
Remove
The response matrices now be- come rank-four tensors

We can identify the interacting and noninteracting response matrices as:
=>
We can redefine the interacting and noninteracting response matrices as (in practice we’ll be using simpler yet equivalent formulae)

In the formula for U in 16.2.2. add the +local also

For the minimum-tracking linear response it would be nice to cite also
G. Moynihan, G. Teobaldi, and D. D. O’Regan, A self-consistent ground-state formulation of the first-principles Hubbard U parameter validated on one-electron self- interaction error (2017), arXiv:1704.08076

Best regards
David

On 8 Aug 2024, at 10:47, JacekDziedzic ***@***.***> wrote:

[External Email] This email originated outside of Trinity College Dublin. Do not click links or open attachments unless you recognise the sender and know the content is safe.


Unsure if we are allowed to publish the OTF pseudos. Apart from that, I only have cosmetic comments. It would be good if a native speaker could polish the text a little.

s/if not refer/if not, refer/
s/choosing and empirical/choosing an empirical/
s/which allow us/which allows us/
s/and label it differently/for, and label it differently/
s/single points calculations/single-point calculations/
s/which corresponds to d-orbitals/, which corresponds to d orbitals./
s/input file the one/input file -- the one/
s/both \alpha and \alpha you need/both \alpha and \beta, you need/
s/remaining 8 file/remaining 8 files/
s/which can be found in the/, which can be found in the/ [twice]
s/note that we are/Note that we are/
s/Next we need/Next, we need/
s/the total occupancy of/The total occupancy of/
s/while local magnetic moment/while the local magnetic moment/
s/the slope we first/the slope, we first/
s/with values of beta to/with values of \beta to/
s/this is VERY/, this is VERY/
s/we would retrieve a wrong value/we would obtain a wrong value/

In the enumeration in 16.2.2 choose whether you use commas between list items and lowercase letters to begin list items, or full stops and capital letters.
In item 4, italicise U and J.
In the formulas that follow, unitalicise 'xc' and 'local'
Missing full stop after \beta at end of p.107.
The list of 7 items under the table is missing full stops.
"The default projectors are NGWFs" -- what other options are there? How do we choose them?
In item 7, at least in the PDF, the \beta did not render correctly, I see the literal text :math:beta.
Any reason for "0.00" and not "0.0" in the table?
Italicise U in "for the U calculation are".
Add full stop after "We now have all the data we need to compute U and J"
Add full stops after list items in "Step by step to..."

**Comment by JacekDziedzic** [comment]
@Nekkrad -- can we get a new PDF, please?

**Comment by Nekkrad** [comment]
> @Nekkrad -- can we get a new PDF, please?

[oneteptutorials.pdf](https://github.com/user-attachments/files/16580675/oneteptutorials.pdf)

As requested

**Comment by david-oregan** [comment]
Looks good @Nekkrad thanks!

**Comment by JacekDziedzic** [comment]
tutorial_15_borked
It looks good to me, except the first image got completely borked in the PDF? See above.

**Comment by JacekDziedzic** [comment]
tutorial_15_borked_2

Hi @Nekkrad -- the image is also borked in the HTML version. Can you please fix this?
Also, these three minor issues:

```
T15_hematite_linear_response.rst:21: ERROR: Unexpected indentation.
T15_hematite_linear_response.rst:288: WARNING: Citation [Linscott2018] is not referenced.
T15_hematite_linear_response.rst:290: WARNING: Citation [Moynihan2017] is not referenced.
```

Once these are fixed, I'm happy to merge.

**Comment by Nekkrad** [comment]
@JacekDziedzic 

Hopefully it should be fine now!

Thanks! 
[oneteptutorials.pdf](https://github.com/user-attachments/files/16659855/oneteptutorials.pdf)

**Comment by JacekDziedzic** [comment]
Excellent! Merging now!

**Pull request merged**
